var welcome_text = "<p>Welcome to the experiment. This experiment should take no longer than 10 minutes.</p> <p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of words. Please try to memorize them. The study is computer mediated and it takes approximately 10 minutes to complete. Also, when prompted to provide the answer, respond by typing in the answer to 2+2. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p>"+"<p>Press any key to begin.</p>";

var attention_check_text = "Provide the answer:"

var fullscreen_prompt = "<p><b>Please turn off all background audio for the experiment</b>. Do not continue until you have turned off all other audio.</p>"+"<p>Also, remain in fullscreen mode for the entire experiment. The experiment will switch to full screen mode when you press the button below. It will also record if you exit fullscreen mode.</p>"

var debrief_text = "<p>In an implicit learning experiment, participants study a list of words that are chosen on the basis of a rule. They are then are asked to classify new test words that conform to that rule. Even though people are never told what the rule is, they are often able to sort rule-following from rule-violating words. We were also interested in recognition performance of these rule based words. In conjunction with this, we are going to use a computational model of human memory, called MINERVA 2, to derive predictions that are consistent with human performance. The ultimate goal of this research is to be able to derive predictions about implicit learning a priori using computational models. This study contained no deception or experimental manipulation of any kind. You can learn more about this line of work from our laboratory webpage located at <b>home.cc.umanitoba.ca/~jamiesor</b> Thank you for your participation, Jackie Spear, University of Manitoba.</p> <p>Press any key to finish the experiment.</p>";

var test_instruction_text = "<p>Take a rest if you need.</p>"+"<p>All of the words you just studied were chosen on the basis of a rule. Next, your job will be to indicate whether you previously studied a word by pressing 'y', otherwise press 'n'. Keep your index fingers on these keys.</p>"+"<p>When you are ready press 'i' to continue.</p>";
